[package]
name = "tinyrust"
version = "0.1.0"
authors = ["ericliu2010 <ericliu2010@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3"
